#!/bin/bash

#enable ctrl-alt-backspace
setxkbmap -option terminate:ctrl_alt_bksp

xrdb -merge .Xresources

#disable annoying beep
xset -b

xrandr --output DVI-0 --left-of DisplayPort-0 --primary

#wallpaper
feh --bg-fill /home/nathan/Pictures/Wallpapers/Fractals\ and\ abstract\ stuff/120825164572.jpg &
#feh --bg-fill /home/nathan/Pictures/mr2_rally_2.jpg &

xscreensaver -no-splash&

wicd-gtk --tray &

udiskie &

dropboxd &

skype &

trayer --edge top --align right --SetDockType true --expand true --width 16 --height 16 --transparent true --alpha 0 --tint 0x000000 --widthtype percent --monitor 0 &

exec xmonad

